spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowable?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
  # redis 配置
  redis:
    # 地址
    host: localhost
    #    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: 123456
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
server:
  port: 7000
fiafeng:
  captcha:
    enable: false
  mysql-table:
    user:
      table-name: sys_user
    permission:
      table-name: base_permission
  mapping:
    enable: true

  rbac:
    permission-aop-enable: true
  security:
    permit-all-list:
      - /login/**
      - /register
      - /captchaImage
      - /modeler/**

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-delete-field: deleted
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

flowable:
  #异步执行
  async-executor-activate: true
  #自动更新数据库
  database-schema-update: true
  #校验流程文件，默认校验resources下的processes文件夹里的流程文件
  process-definition-location-prefix: classpath*:/processes/
  process-definition-location-suffixes: "**.bpmn20.xml, **.bpmn"
  #该配置只是防止页面报错,没有实际意义
  common:
    app:
      idm-admin:
        password: test
        user: test
      #没有实际意义
      idm-url: http://localhost:8080/flowable-demo
